# -*- coding: utf-8 -*-
"""Ejercicio1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nESZqYy6fW4S-qiEN0TZsH4AzhcROZkQ
"""

continua= True
x= 0
z= 0
x= int(input("Dame el valor inicial "))
#print(type(x))
z= int(input("Dame el valor final "))
#print(z)
if x > z:
  print("El primer valor no puede ser mayor que el segundo")
  continua= False
elif z < x:
  print("El segundo valor no puede ser menor que el primero")
  continua= False

if continua:
  numbers = range(x,z+1)
  cadena= ""
  for y in numbers:
    if (y%3 == 0) and (y%5 == 0):
      cadena= cadena+"Fizz Buzz, "
    elif y % 3 == 0:
      #print("Fizz")
      cadena= cadena+"Fizz, "
    elif y % 5 == 0:
      #print("Buzz")
      cadena= cadena+"Buzz, "
    else:
      #print(y)
      cadena= cadena+ str(y)+", "
  print(cadena)